name: Build rpi-image-gen with QEMU aarch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this workflow repo
        uses: actions/checkout@v4

      - name: Import missing Debian repo GPG keys
        run: |
          sudo apt-get install -y gnupg2 curl
          for key in 0E98404D386FA1D9 6ED0E7B82643E131 F8D2585B8783D481 54404762BBB6E853 BDE6D2B9216EC7A8 78DBA3BC47EF2265; do
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $key || \
            curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x${key}" | sudo gpg --dearmor -o /usr/share/keyrings/${key}.gpg
          done

      - name: Install QEMU and binfmt support
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo modprobe binfmt_misc
          sudo mount -t binfmt_misc none /proc/sys/fs/binfmt_misc || true
          sudo update-binfmts --enable qemu-aarch64

      - name: Checkout rpi-image-gen repo
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/rpi-image-gen
          path: rpi-image-gen

      - name: Make scripts executable
        run: chmod +x rpi-image-gen/install_deps.sh rpi-image-gen/build.sh

      - name: Run install_deps.sh script
        working-directory: rpi-image-gen
        run: sudo ./install_deps.sh

      - name: Run build.sh script
        run: ./rpi-image-gen/build.sh -o ./base/base.options -c ./base/config/base.cfg

      - name: Compress built image with xz
        run: |
          xz -9 /home/runner/work/RatOS-rpi64/RatOS-rpi64/rpi-image-gen/work/deb12-arm64-min/deploy/deb12-arm64-min.img
        # This creates deb12-arm64-min.img.xz next to the original image

